kind: pipeline
type: docker
name: deploy-dev-direct-password

trigger:
  branch:
    - develop
  event:
    - push


services:
  - name: docker
    image: docker:dind

steps:
  - name: build-and-save-image
    image: docker:latest
    commands:
      - sleep 15
      - docker build -f Dockerfile.prod -t hikka-dev:latest .
      - docker save hikka-dev:latest -o hikka-dev-image.tar

  - name: copy-image-to-server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: DEV_SERVER_HOST
      username:
        from_secret: DEV_SERVER_USER
      password:
        from_secret: DEV_SERVER_PASSWORD
      source: hikka-dev-image.tar
      target: /tmp/
    depends_on:
      - build-and-save-image

  - name: deploy-on-server
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEV_SERVER_HOST
      username:
        from_secret: DEV_SERVER_USER
      password:
        from_secret: DEV_SERVER_PASSWORD
      script:
        - docker load -i /tmp/hikka-dev-image.tar
        - docker stop hikka-dev-container || true
        - docker rm hikka-dev-container || true
        - >
          docker run -d
          --restart always
          --name hikka-dev-container
          -p 3001:3000
          hikka-dev:latest
        - rm /tmp/hikka-dev-image.tar
    depends_on:
      - copy-image-to-server
